apiVersion: v1
items:
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: zookeeper
    namespace: default
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: zookeeper
    serviceName: zookeeper-headless
    template:
      metadata:
        labels:
          app: zookeeper
        name: zookeeper
      spec:
#        affinity:
#          podAntiAffinity:
#            requiredDuringSchedulingIgnoredDuringExecution:
#            - labelSelector:
#                matchExpressions:
#                - key: app
#                  operator: In
#                  values:
#                  - zookeeper
#              topologyKey: kubernetes.io/hostname
        imagePullSecrets:
        - name: docker-regsitry-auth
        containers:
        - command:
          - sh
          - -c
          - start-zookeeper --servers=3 --data_dir=/var/lib/zookeeper/data --data_log_dir=/var/lib/zookeeper/data/log
            --conf_dir=/opt/zookeeper/conf --client_port=2181 --election_port=3888
            --server_port=2888 --tick_time=2000 --init_limit=10 --sync_limit=5 --heap=512M
            --max_client_cnxns=60 --snap_retain_count=3 --purge_interval=12 --max_session_timeout=40000
            --min_session_timeout=4000 --log_level=INFO
          image: lizhenliang/kubernetes-zookeeper:1.0-3.4.10
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - zookeeper-ready 2181
            initialDelaySeconds: 10
            periodSeconds: 10
          name: kubernetes-zookeeper
          ports:
          - containerPort: 2181
            name: client
            protocol: TCP
          - containerPort: 2888
            name: server
            protocol: TCP
          - containerPort: 3888
            name: leader-election
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - zookeeper-ready 2181
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
          - mountPath: /var/lib/zookeeper
            name: datadir
    updateStrategy:
      type: RollingUpdate
    volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        storageClassName: "managed-nfs-storage"
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper
  name: zookeeper-headless
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: client
    port: 2181
    protocol: TCP
    targetPort: client
  - name: follower
    port: 2888
    protocol: TCP
    targetPort: follower
  - name: election
    port: 3888
    protocol: TCP
    targetPort: election
  selector:
    app: zookeeper
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper
  name: zookeeper-service
  namespace: default
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    app: zookeeper
  type: ClusterIP
